### ISSUE TITLE
Cannot Update or Delete Courses from Google Classroom

### ISSUE THREAD

**Issue by bmcced** [jay0lee/GAM#1005]
I have about 30 courses in my system which give me an "Error 500" when I attempt to archive or delete:

```
gam update course 5953220 status ARCHIVED
ERROR: 500: Internal error encountered. - 500
```
Alternatively
```
gam delete course 5953220
ERROR: 500: Internal error encountered. - 500
```
However, I can clearly interact with the course by ID:
```
gam info course 5953220

 id: 5953220
 name: Foundations of Theater (section 02)
 section: E Period
 descriptionHeading: Foundations of Theater
 description: Welcome to theater.  This class is going to be a lot of fun.  We will explore all different styles of theater and will work together as an ensemble.
 room: 102
 ownerId: 105250506097979753968
 creationTime: 2014-09-09T01:38:52.187Z
 updateTime: 2014-09-09T20:49:12.511Z
 enrollmentCode: zi7le
 courseState: ACTIVE
 alternateLink: https://classroom.google.com/c/NTk1MzIyMFpa
 teacherGroupEmail: Foundations_of_Theater__section_02__E_Period_teachers_ewZP9A@mmfsnyc.org
 courseGroupEmail: Foundations_of_Theater__section_02_--ewZP9A@mmfsnyc.org
 courseMaterialSets:

   title: Foundation of Theater Syllabus
   materials:

     driveFile:

      id: 1VHSQTY-89eN0j9Mi98Ctm5GLtIK04PhTN23WAhxmaBc
      alternateLink: https://drive.google.com/open?id=1VHSQTY-89eN0j9Mi98Ctm5GLtIK04PhTN23WAhxmaBc
 guardiansEnabled: False
 ownerEmail: 105250506097979753968
Participants:
 Teachers:
 Students:
  Bill Cipher - emilyk@alum.mmfsnyc.org
  Henry Belman - henryb@alum.mmfsnyc.org
  Natasha Rotterdam - natashar@alum.mmfsnyc.org
  Parker Ciuzio - parkerc@alum.mmfsnyc.org
```

My only supposition is that the teacher who owned the course is no longer in the domain, but that shouldn't stop the central admin from deleting, even if it screws with archiving, no?
