### ISSUE TITLE
Update internal organization information

### ISSUE THREAD

**Issue by justinmartin** [jay0lee/GAM#39]
From the documentation it only appears that we can add external organizational information.  Is it possible to edit the internal description and title of a user via GAM?

Here is relevant section of `gam info user`

```
Organizations:
 customType:
 description: Staff
 title: Technology Coordinator
```

I'd love set title for everyone in the district without updating each by hand.
